import { ROLES } from './roles.js';

export const PERMISSIONS = Object.freeze({
  DASHBOARD_READ: 'dashboard:read',
  LEADS_READ: 'leads:read',
  LEADS_WRITE: 'leads:write',
  LEADS_ASSIGN: 'leads:assign',
  INQUIRIES_READ: 'inquiries:read',
  INQUIRIES_WRITE: 'inquiries:write',
  PROJECTS_READ: 'projects:read',
  PROJECTS_WRITE: 'projects:write',
  TALKS_READ: 'talks:read',
  TALKS_WRITE: 'talks:write',
  SPEAKERS_READ: 'speakers:read',
  SPEAKERS_WRITE: 'speakers:write',
  SERVICES_READ: 'services:read',
  SERVICES_WRITE: 'services:write',
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  SETTINGS_READ: 'settings:read',
  SETTINGS_WRITE: 'settings:write',
  AUDIT_READ: 'audit:read',
});

const ALL_STAFF = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.STAFF,
  ROLES.CONTENT_MANAGER,
  ROLES.SALES,
];

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.LEADS_ASSIGN,
    PERMISSIONS.INQUIRIES_READ,
    PERMISSIONS.INQUIRIES_WRITE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.TALKS_READ,
    PERMISSIONS.TALKS_WRITE,
    PERMISSIONS.SPEAKERS_READ,
    PERMISSIONS.SPEAKERS_WRITE,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_WRITE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.SALES]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.LEADS_ASSIGN,
    PERMISSIONS.INQUIRIES_READ,
    PERMISSIONS.INQUIRIES_WRITE,
  ],
  [ROLES.CONTENT_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.TALKS_READ,
    PERMISSIONS.TALKS_WRITE,
    PERMISSIONS.SPEAKERS_READ,
    PERMISSIONS.SPEAKERS_WRITE,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_WRITE,
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.INQUIRIES_READ,
    PERMISSIONS.INQUIRIES_WRITE,
  ],
  [ROLES.USER]: [],
});

export function roleHasPermission(role, permission) {
  const list = ROLE_PERMISSIONS[role] || [];
  return list.includes(permission);
}

export function permissionsForRole(role) {
  return [...(ROLE_PERMISSIONS[role] || [])];
}

export function isStaffRole(role) {
  return ALL_STAFF.includes(role);
}

export { ALL_STAFF };
